"""Honest classification: which subsystems are universal, namespaced, or venue-specific."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from trading_ai.runtime_paths import ezras_runtime_root


def _items() -> List[Dict[str, Any]]:
    return [
        _row(
            "Universal ratio registry",
            "trading_ai.ratios.universal_ratio_registry",
            "universal_with_namespacing",
            "universal_with_namespacing",
            "Low — gate overlays keyed by gate_id",
            True,
            False,
            ["avenue_id", "gate_id", "strategy_id"],
            True,
            True,
            "Overlays are gate_a / gate_b; future gates add keys without merging blobs.",
        ),
        _row(
            "Reserve / deployable reports",
            "trading_ai.ratios.reserve_compute + capital_reports",
            "avenue_specific",
            "should_be_split_into_universal_plus_specific",
            "Medium — deployable JSON is Coinbase-centric today",
            True,
            True,
            ["avenue_id", "venue_name"],
            False,
            False,
            "Universal math; venue truth source must stay per avenue.",
        ),
        _row(
            "Gap closure / honest live matrix",
            "trading_ai.ratios.gap_closure",
            "universal_now",
            "universal_with_namespacing",
            "Low",
            True,
            False,
            ["artifact_scope"],
            True,
            True,
            "System-level truth table; extend rows per avenue in matrix builder later.",
        ),
        _row(
            "Gate A live truth snapshot",
            "trading_ai.deployment.gate_a_live_truth",
            "gate_specific",
            "gate_specific",
            "Low — read-only advisory",
            True,
            True,
            ["gate_id", "avenue_id"],
            True,
            True,
            "Pattern reusable; content is Gate A.",
        ),
        _row(
            "Gate B live status",
            "trading_ai.shark.coinbase_spot.gate_b_live_status",
            "gate_specific",
            "gate_specific",
            "Low",
            True,
            True,
            ["gate_id", "avenue_id"],
            True,
            True,
            "Kalshi Gate B only; do not merge with Gate A execution.",
        ),
        _row(
            "Readiness / final readiness",
            "trading_ai.deployment.readiness_decision",
            "universal_now",
            "universal_with_namespacing",
            "Medium if flattened",
            False,
            True,
            ["system"],
            True,
            True,
            "Keep system-wide; add per-avenue sections via separate keys later.",
        ),
        _row(
            "CEO daily review (generic)",
            "trading_ai.review.ceo_review_session",
            "universal_now",
            "universal_with_namespacing",
            "Medium — today single global diagnosis",
            True,
            False,
            ["session_scope", "avenue_id", "gate_id"],
            True,
            True,
            "Use scoped wrappers; legacy flat ceo_daily_review.json remains.",
        ),
        _row(
            "Daily ratio review",
            "trading_ai.ratios.daily_ratio_review",
            "universal_now",
            "universal_with_namespacing",
            "Low",
            True,
            False,
            ["avenue_id", "gate_id"],
            True,
            True,
            "Scoped copies under data/review/avenues/...",
        ),
        _row(
            "Databank schema + ratio fold",
            "trading_ai.nte.databank.databank_schema",
            "universal_now",
            "universal_with_namespacing",
            "Low if avenue columns present on rows",
            True,
            False,
            ["avenue_id", "gate_id", "trading_gate"],
            True,
            True,
            "Rows already carry avenue/strategy; keep strict on ingest.",
        ),
        _row(
            "Trade ratio context builder",
            "trading_ai.ratios.trade_ratio_context",
            "universal_with_namespacing",
            "universal_with_namespacing",
            "Low",
            True,
            False,
            ["trading_gate", "avenue_id"],
            True,
            True,
            "Advisory context; gate overlays keyed by name.",
        ),
        _row(
            "Validation resolve / runtime policy",
            "trading_ai.nte.execution.routing.integration.validation_resolve",
            "venue_specific",
            "should_be_split_into_universal_plus_specific",
            "High if mis-applied to non-Coinbase",
            False,
            True,
            ["venue_name", "avenue_id"],
            False,
            False,
            "Coinbase NTE path — do not treat as universal execution router.",
        ),
        _row(
            "Adaptive OS / live adaptive",
            "trading_ai.control.live_adaptive_integration",
            "universal_now",
            "universal_with_namespacing",
            "Medium",
            True,
            False,
            ["avenue_id", "gate_id"],
            True,
            True,
            "Proof artifacts global today; scope per avenue when extending.",
        ),
        _row(
            "Edge registry (local)",
            "trading_ai.edge",
            "universal_with_namespacing",
            "universal_with_namespacing",
            "Medium without avenue columns",
            True,
            False,
            ["edge_id", "avenue_id", "gate_id"],
            True,
            True,
            "Ensure edge rows carry venue/avenue when mirroring to Supabase.",
        ),
        _row(
            "Safest edges ranking",
            "trading_ai.evolution.safest",
            "universal_now",
            "universal_with_namespacing",
            "Medium",
            True,
            False,
            ["avenue_id", "gate_id"],
            True,
            True,
            "Filter lists by scope before comparing across venues.",
        ),
        _row(
            "Kalshi simple scanner",
            "trading_ai.shark.kalshi_simple_scanner",
            "scanner_specific",
            "scanner_specific",
            "Low within Kalshi",
            False,
            True,
            ["avenue_id", "gate_id", "scanner_id"],
            False,
            True,
            "Gate B scanner logic — not reusable as-is for Coinbase.",
        ),
        _row(
            "Coinbase NTE engine",
            "trading_ai.nte.execution.coinbase_engine",
            "execution_specific",
            "venue_specific",
            "High cross-venue",
            False,
            True,
            ["venue_name", "avenue_id"],
            False,
            False,
            "Never generalize execution API — keep isolated.",
        ),
        _row(
            "System mastery / recent work audit",
            "trading_ai.ratios.system_mastery + recent_work_activation",
            "universal_now",
            "universal_with_namespacing",
            "Low",
            True,
            False,
            ["artifact_scope"],
            True,
            True,
            "Add per-avenue audit files alongside system files.",
        ),
        _row(
            "Integration structural audit",
            "trading_ai.ratios.integration_structural_audit",
            "universal_now",
            "universal_now",
            "Low",
            True,
            False,
            ["component_id"],
            True,
            True,
            "Curated map — update when adding avenues.",
        ),
        _row(
            "Research / GPT hooks",
            "trading_ai.intake.gpt_researcher_hooks",
            "universal_now",
            "universal_with_namespacing",
            "Medium",
            True,
            False,
            ["avenue_id", "session_scope"],
            True,
            True,
            "Attach research sessions to scope explicitly.",
        ),
        _row(
            "Multi-avenue framework (this package)",
            "trading_ai.multi_avenue",
            "universal_now",
            "universal_now",
            "Low",
            True,
            False,
            ["avenue_id", "gate_id"],
            True,
            True,
            "Registries + scoped dirs — no execution.",
        ),
    ]


def _row(
    module_or_feature_name: str,
    current_location: str,
    current_scope: str,
    recommended_scope: str,
    contamination_risk: str,
    safe_to_universalize_now: bool,
    should_remain_specific: bool,
    required_namespace_keys: List[str],
    automatic_for_new_avenues: bool,
    automatic_for_new_gates: bool,
    notes: str,
) -> Dict[str, Any]:
    return {
        "module_or_feature_name": module_or_feature_name,
        "current_location": current_location,
        "current_scope": current_scope,
        "recommended_scope": recommended_scope,
        "contamination_risk": contamination_risk,
        "safe_to_universalize_now": safe_to_universalize_now,
        "should_remain_specific": should_remain_specific,
        "required_namespace_keys": required_namespace_keys,
        "automatic_for_new_avenues": automatic_for_new_avenues,
        "automatic_for_new_gates": automatic_for_new_gates,
        "notes": notes,
    }


def build_multi_avenue_universalization_audit(*, runtime_root: Path | None = None) -> Dict[str, Any]:
    root = Path(runtime_root or ezras_runtime_root()).resolve()
    return {
        "artifact": "multi_avenue_universalization_audit",
        "version": "v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "runtime_root": str(root),
        "classification_legend": {
            "universal_now": "Already safe across venues when scope labels exist.",
            "universal_with_namespacing": "Needs explicit avenue/gate/strategy keys in artifacts.",
            "avenue_specific": "Different instance per avenue.",
            "gate_specific": "Different behavior per gate.",
            "venue_specific": "Tied to exchange API semantics.",
            "scanner_specific": "Scanner implementation tied to market/venue.",
            "execution_specific": "Order placement / fills — never mush into universal blob.",
            "should_be_split_into_universal_plus_specific": "Split pattern vs venue implementation.",
            "currently_misplaced": "Would benefit from relocation or scoped wrapper.",
        },
        "items": _items(),
    }


def write_universalization_audit_files(
    *,
    runtime_root: Path | None = None,
) -> Dict[str, str]:
    root = Path(runtime_root or ezras_runtime_root()).resolve()
    ctrl = root / "data" / "control"
    ctrl.mkdir(parents=True, exist_ok=True)
    payload = build_multi_avenue_universalization_audit(runtime_root=root)
    js = json.dumps(payload, indent=2, default=str)
    jp = ctrl / "multi_avenue_universalization_audit.json"
    tp = ctrl / "multi_avenue_universalization_audit.txt"
    jp.write_text(js, encoding="utf-8")
    tp.write_text(js[:32000] + "\n", encoding="utf-8")
    return {
        "multi_avenue_universalization_audit_json": str(jp),
        "multi_avenue_universalization_audit_txt": str(tp),
    }
